/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as http from "../http.js";
import type * as list_notification_types from "../list_notification_types.js";
import type * as list_snippet_types from "../list_snippet_types.js";
import type * as snippet_type_and_data_mapping from "../snippet_type_and_data_mapping.js";
import type * as snippets from "../snippets.js";
import type * as user_notifications from "../user_notifications.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  http: typeof http;
  list_notification_types: typeof list_notification_types;
  list_snippet_types: typeof list_snippet_types;
  snippet_type_and_data_mapping: typeof snippet_type_and_data_mapping;
  snippets: typeof snippets;
  user_notifications: typeof user_notifications;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
